# Generated by Django 3.0.2 on 2021-04-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
    ]
